### ISSUE TITLE
Too much output in webpack-dev-server

### ISSUE THREAD

**Issue by ryanmk54** [simbathesailor/babel-plugin-use-what-changed#15]
Thank you for this amazing plugin! There is one problem. When I run webpack-dev-server, it adds a ton of output before outputting the packs. It looks like it is outputting my entire source code as well as other things. Is there a way to remove this?

**Comment by simbathesailor** [comment]
Thanks for pointing out the issue. It has been fixed in this pr.

https://github.com/simbathesailor/babel-plugin-use-what-changed/pull/14. Please read the pr comments to fix the extra log which is haeppening

**Comment by ryanmk54** [comment]
Thank you. Sorry, I should've checked the pull requests before opening an issue.
